---
title: "[Issue ID] | PR Title"
---

<!-- Please ensure your PR title follows the pattern:
[Issue ID] | Short description of the changes made
-->

**Discord Username:** @<your-username>

---

## What type of PR is this? (select all that apply)

- [ ] 🍕 Feature  
- [ ] 🐛 Bug Fix  
- [ ] 🚧 Breaking Change  
- [ ] 🧑‍💻 Code Refactor  
- [ ] 📝 Documentation Update

---

## Description  
<!-- Please include a summary of the changes made and what issue is fixed.
Also provide relevant context and list any dependencies required for the change. -->

---

## Related Tickets & Documents  
- Related Issue: #  
- Closes: #  

---

## QA Instructions, Screenshots, Recordings  
<!-- Provide detailed instructions on how the reviewer can test your changes.
Mention any devices or browsers used for testing, and include screenshots or recordings if applicable. -->

---

### UI Accessibility Concerns  
<!-- If your PR involves UI changes, please describe how accessibility is handled. -->

---

## Added/Updated Tests?  
- [ ] 👍 Yes  
- [ ] 🙅 No, not needed  
- [ ] 🙋 No, but I need help  

---

## Are there any post-deployment tasks? (Optional)  
<!-- List any tasks required after deployment, if applicable. -->

---

## What GIF best describes this PR or how it makes you feel? (Optional)  
<!-- Feel free to add a fun GIF that summarizes your PR or your emotions! -->
