# Pull Request Template

## Thanks for your contribution! 🎉  
Please follow the guidelines outlined in our [CONTRIBUTING.md](../CONTRIBUTING.md) file.

### **Naming Convention Summary**
- **PR Title:** `[ISSUE ID] | Short description of PR`
- **Branch Name:** `[ISSUE ID]-short-description`
- **Commit Format:** `[[ISSUE ID]] [ACTION]: what was done`

**Example:**
```text
PR: #2 Add Docker container for Postgres  
Branch: 2-add-container-postgres  
Commit: [2] feat: add docker container for postgres
