name: Bug Report
description: Create a bug report to help us improve
title: "[BUG]: "
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this bug report!

  - type: checkboxes
    id: confirmation
    attributes:
      label: Please confirm the following before submitting the issue:
      options:
        - label: I am running the latest version.
          required: true
        - label: I checked the documentation and found no answer.
          required: true
        - label: I verified that this issue has not already been filed.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Try to describe what happened, including any relevant context or steps.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: "1. Go to...\n2. Click on...\n3. See the issue..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "The feature should..."

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "What happened instead..."

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
