name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Provide a clear and concise description of the feature or enhancement."
      placeholder: "What would you like to see added or improved?"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this feature is important or useful."
      placeholder: "Why is this feature necessary or beneficial?"

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Describe any other solutions or alternatives you've thought of."
      placeholder: "What other options did you consider?"

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: "By submitting this feature request, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)."
      options:
        - label: "I agree to follow this project's Code of Conduct."
          required: true
